var json_Geburtsbriefe_geokodiertGROUPS_2 = {
"type": "FeatureCollection",
"name": "Geburtsbriefe_geokodiertGROUPS_2",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Archival record": "G \/ 1596 Juni 17", "Title": "Geburtsbrief für Gertraud Emert und ihre Geschwister Kasper Emert und Margreth Emert von Florenberg [Gem. Künzell] bzw. Edelzell bei Fulda", "Recipient's gender": "m\/f", "Language": "de", "Issuer": "Fuldaer Zentgraf Wilhelm Opfermann und Schöffen des Zent- und Landgerichts. S. des Zentgrafen Wilhelm Opfermann.", "Date": "17.06.1596", "Archival provenance": "Stadt Mainz", "Permalink": "https:\/\/faust.mainz.de\/objekt_start.fau?prj=internet&dm=archiv&zeig=105394", "Related place 1": "Edelzell", "Related place 2": "Florenberg", "Related place 3": "Fulda", "Related place 4": "Künzell", "Recipient's place of origin": "Fulda", "data reliability": "automatically assigned via GOOGLE API" }, "geometry": { "type": "Point", "coordinates": [ 9.6808449, 50.5558095 ] } },
{ "type": "Feature", "properties": { "Archival record": "G \/ 1613 Februar 28", "Title": "Geburtsbrief für Michael Heimberger aus Pülfringen (Kr. Mosbach) und seine Frau Margarethe Munch", "Recipient's gender": "m\/f", "Language": "de", "Issuer": "Amtmann von Schweinberg.", "Date": "28.02.1613", "Archival provenance": "Stadt Mainz", "Permalink": "https:\/\/faust.mainz.de\/objekt_start.fau?prj=internet&dm=archiv&zeig=123367", "Related place 1": "Mosbach", "Related place 2": "Pülfringen", "Related place 3": "Schweinberg", "Related place 4": "#", "Recipient's place of origin": "Schweinberg", "data reliability": "automatically assigned via GOOGLE API" }, "geometry": { "type": "Point", "coordinates": [ 9.518722, 49.6198919 ] } },
{ "type": "Feature", "properties": { "Archival record": "G \/ 1634 Januar 26", "Title": "Geburtsbrief für Mich(a)el Urban von Nüdlingen und seine Kinder Hans\/ Konrad\/ Georg\/ Balthasar und Barbara von Würzburg", "Recipient's gender": "m\/f", "Language": "de", "Issuer": "Stadt Würzburg. S. der Stadt.", "Date": "26.01.1634", "Archival provenance": "Stadt Mainz", "Permalink": "https:\/\/faust.mainz.de\/objekt_start.fau?prj=internet&dm=archiv&zeig=123453", "Related place 1": "Nüdlingen\/ Würzburg", "Related place 2": "#", "Related place 3": "#", "Related place 4": "#", "Recipient's place of origin": "Würzburg", "data reliability": "automatically assigned via GOOGLE API" }, "geometry": { "type": "Point", "coordinates": [ 9.9533548, 49.7913044 ] } },
{ "type": "Feature", "properties": { "Archival record": "G \/ 1644 November 1", "Title": "Geburtsbrief für Jakob Kreißing von Urbar b. Ehrenbreitstein und seine Frau Margarethe", "Recipient's gender": "m\/f", "Language": "de", "Issuer": "Urbar. Siegel d. Ausstellers.", "Date": "01.11.1644", "Archival provenance": "Stadt Mainz", "Permalink": "https:\/\/faust.mainz.de\/objekt_start.fau?prj=internet&dm=archiv&zeig=123734", "Related place 1": "Ehrenbreitstein", "Related place 2": "Urbar", "Related place 3": "#", "Related place 4": "#", "Recipient's place of origin": "Urbar", "data reliability": "automatically assigned via GOOGLE API" }, "geometry": { "type": "Point", "coordinates": [ 7.6258037, 50.380687 ] } },
{ "type": "Feature", "properties": { "Archival record": "G \/ 1654 August 21", "Title": "Geburtsbrief für die Kinder von Schneidermeister Michael Khimberle von Bruneck (Südtirol): Andreas\/ Abraham\/ Kasper\/ Michael\/ Simon und Maria", "Recipient's gender": "m\/f", "Language": "de", "Issuer": "#", "Date": "21.08.1654", "Archival provenance": "Stadt Mainz", "Permalink": "https:\/\/faust.mainz.de\/objekt_start.fau?prj=internet&dm=archiv&zeig=124081", "Related place 1": "Bruneck", "Related place 2": "Südtirol", "Related place 3": "#", "Related place 4": "#", "Recipient's place of origin": "Bruneck", "data reliability": "automatically assigned via GOOGLE API" }, "geometry": { "type": "Point", "coordinates": [ 11.9515441, 46.788606 ] } },
{ "type": "Feature", "properties": { "Archival record": "G \/ 1667 September 17", "Title": "Geburtsbrief für Mathias \/ Martin \/ Paul (Schuhmacher) \/ Hans Georg und Eva Rosina Paumgartner von Wels (Ober-Österreich)", "Recipient's gender": "m\/f", "Language": "de", "Issuer": "Stadt Wels. S. der Stadt.", "Date": "17.09.1667", "Archival provenance": "Stadt Mainz", "Permalink": "https:\/\/faust.mainz.de\/objekt_start.fau?prj=internet&dm=archiv&zeig=124331", "Related place 1": "Ober-Österreich", "Related place 2": "Wels", "Related place 3": "#", "Related place 4": "#", "Recipient's place of origin": "Wels", "data reliability": "automatically assigned via GOOGLE API" }, "geometry": { "type": "Point", "coordinates": [ 14.0267477, 48.1687374 ] } },
{ "type": "Feature", "properties": { "Archival record": "G \/ 1670 September 15", "Title": "Geburtsbriefe für Nikolaus Wolf und seine Frau Magdalena Schmid von Bodenheim", "Recipient's gender": "m\/f", "Language": "de", "Issuer": "#", "Date": "15.09.1670", "Archival provenance": "Stadt Mainz", "Permalink": "https:\/\/faust.mainz.de\/objekt_start.fau?prj=internet&dm=archiv&zeig=124378", "Related place 1": "Bodenheim", "Related place 2": "#", "Related place 3": "#", "Related place 4": "#", "Recipient's place of origin": "Bodenheim", "data reliability": "unclear: places of same name in North Rhine Westphalia! Which one?" }, "geometry": { "type": "Point", "coordinates": [ 8.18, 49.56 ] } },
{ "type": "Feature", "properties": { "Archival record": "G \/ 1680 Januar 9 bzw. 1680 Januar 19", "Title": "Geburtsbriefe für Abraham Neumann\/ Agnes Neumann und Anna Dorothea Neumann von Frankfurt a. Main.", "Recipient's gender": "m\/f", "Language": "de", "Issuer": "Stadt Frankfurt am Main", "Date": "09.01.1680", "Archival provenance": "Stadt Mainz", "Permalink": "https:\/\/faust.mainz.de\/objekt_start.fau?prj=internet&dm=archiv&zeig=125317", "Related place 1": "Frankfurt a. Main", "Related place 2": "#", "Related place 3": "#", "Related place 4": "#", "Recipient's place of origin": "Frankfurt a. Main", "data reliability": "automatically assigned via GOOGLE API" }, "geometry": { "type": "Point", "coordinates": [ 8.6821267, 50.1109221 ] } },
{ "type": "Feature", "properties": { "Archival record": "G \/ 1690 Oktober 30", "Title": "Geburtsbrief für Lipfinger\/ Kinder des Andreas\/ verheiratet mit Barbara: Lorenz\/ Eva Katharina und Barbara von Wels (O.-Öst.).", "Recipient's gender": "m\/f", "Language": "de", "Issuer": "Stadt", "Date": "30.10.1690", "Archival provenance": "Stadt Mainz", "Permalink": "https:\/\/faust.mainz.de\/objekt_start.fau?prj=internet&dm=archiv&zeig=123915", "Related place 1": "Wels", "Related place 2": "", "Related place 3": "#", "Related place 4": "#", "Recipient's place of origin": "Wels", "data reliability": "manually corrected" }, "geometry": { "type": "Point", "coordinates": [ 14.0267477, 48.1687374 ] } },
{ "type": "Feature", "properties": { "Archival record": "G \/ 1713 Juli 18", "Title": "Geburtsbrief für Franz Adam \/ Ursula und Christina Schäffer von Nürnberg (?)", "Recipient's gender": "m\/f", "Language": "de", "Issuer": "Gall Heinrich Bauer (Protonotar und Pfalzgraf)", "Date": "18.07.1713", "Archival provenance": "Stadt Mainz", "Permalink": "https:\/\/faust.mainz.de\/objekt_start.fau?prj=internet&dm=archiv&zeig=123898", "Related place 1": "Bamberg", "Related place 2": "Nürnberg", "Related place 3": "#", "Related place 4": "#", "Recipient's place of origin": "Bamberg", "data reliability": "automatically assigned via GOOGLE API" }, "geometry": { "type": "Point", "coordinates": [ 10.8911132, 49.8972487 ] } }
]
}
